Repository HabitPay/backend, pull requests merged in 2024-07, with the labels that each got.

#103 [feat] 포스트 업로드 시 record 객체 생성 로직 초안 #101
  src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/dao/ChallengeParticipationRecordRepository.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
Labels: enhancement

#105 [feat] 챌린지 포스트의 postPhoto 저장 시, S3에 업로드 되는 경로 이름 구체화하기 #104
  src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoCreationService.java
Labels: enhancement

#108 [feat] 쿼리 메서드를 이용해 alreadyParticipateToday 메서드 단순화하기 #107
  src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/dao/ChallengeParticipationRecordRepository.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
Labels: enhancement

#110 refact/change_name_of_method_realted_with_alreadyParticipateToday#109
  src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
Labels: enhancement

#111 Chore/spring rest docs 적용#102
  .github/workflows/api-docs.yaml
  build.gradle
  src/docs/asciidoc/api/member.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/test.adoc
  src/main/java/com/habitpay/habitpay/HabitpayApplication.java
  src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeResponse.java
  src/main/java/com/habitpay/habitpay/domain/member/api/MemberApi.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberSearchService.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/MemberResponse.java
  src/main/java/com/habitpay/habitpay/domain/restdocs/RestDocsController.java
  src/main/java/com/habitpay/habitpay/global/config/JpaConfiguration.java
  src/test/java/com/habitpay/habitpay/HabitpayApplicationTests.java
  src/test/java/com/habitpay/habitpay/RestDocsControllerTest.java
  src/test/java/com/habitpay/habitpay/docs/springrestdocs/AbstractRestDocsTests.java
  src/test/java/com/habitpay/habitpay/member/api/MemberApiTest.java
  src/test/resources/application.yaml
Labels: enhancement

#114 [feat] SchedulerConfiguration 클래스 생성 #113
  src/main/java/com/habitpay/habitpay/global/config/SchedulerConfiguration.java
Labels: enhancement

#116 [Feat] POST /api/member 경로를 위한 인터셉터 설정 수정 #115
  src/main/java/com/habitpay/habitpay/global/config/auth/CorsConfig.java
  src/main/java/com/habitpay/habitpay/global/config/auth/interceptor/AuthorizationInterceptor.java
  src/main/java/com/habitpay/habitpay/global/config/auth/interceptor/SignUpInterceptor.java
Labels: enhancement

#119 [feat] 회원가입용 인터셉터와 인증 인터셉터를 하나로 합치기#118
  src/main/java/com/habitpay/habitpay/global/config/auth/CorsConfig.java
  src/main/java/com/habitpay/habitpay/global/config/auth/interceptor/AuthorizationInterceptor.java
  src/main/java/com/habitpay/habitpay/global/config/auth/interceptor/SignUpInterceptor.java
Labels: enhancement

#122 [fix] 인터셉터 수정 #121
  src/main/java/com/habitpay/habitpay/global/config/auth/interceptor/AuthorizationInterceptor.java
Labels: enhancement

#123 [feat] 벌금 현황 조회 서비스 만들기 & 멤버와 챌린지 정보로 enrollment 객체 찾기 서비스 #120
  src/main/java/com/habitpay/habitpay/domain/ChallengeAbsenceFee/application/ChallengeAbsenceFeeSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/dao/ChallengeEnrollmentRepository.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
Labels: enhancement

#125 [refact] 반복되는 코드 없애기, 반환값 애매한 부분에 주석 추가 #124
  src/main/java/com/habitpay/habitpay/domain/ChallengeAbsenceFee/application/ChallengeAbsenceFeeSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
Labels: enhancement

#127 [feat] 벌금 현황 조회 서비스에서 조회에 필요한 객체를 찾지 못했을 경우, 예외를 던진다 #126
  src/main/java/com/habitpay/habitpay/domain/ChallengeAbsenceFee/application/ChallengeAbsenceFeeSearchService.java
Labels: enhancement

#129 Feat/status 2xx 공통 response 구현#117
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeUpdateService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApi.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeCancellationService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentService.java
  src/main/java/com/habitpay/habitpay/domain/member/api/MemberApi.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberActivationService.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberCreationService.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/MemberActivationRequest.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/MemberActivationResponse.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/MemberCreationResponse.java
  src/main/java/com/habitpay/habitpay/global/config/auth/CustomOAuth2LoginSuccessHandler.java
  src/main/java/com/habitpay/habitpay/global/config/auth/CustomOAuth2UserService.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/TokenProvider.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/TokenService.java
  src/main/java/com/habitpay/habitpay/global/response/ApiResponse.java
  src/main/java/com/habitpay/habitpay/global/response/SuccessResponse.java
  src/test/java/com/habitpay/habitpay/domain/api/MemberApiTest.java
Labels: enhancement

#131 Feat/request header 에 jwt 확인을 위한 interceptor 제거 및 filter 추가#130
  src/main/java/com/habitpay/habitpay/domain/ChallengeAbsenceFee/application/ChallengeAbsenceFeeSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/dao/ChallengeEnrollmentRepository.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
  src/main/java/com/habitpay/habitpay/global/config/auth/CorsConfig.java
  src/main/java/com/habitpay/habitpay/global/config/auth/SecurityConfig.java
  src/main/java/com/habitpay/habitpay/global/config/auth/interceptor/AuthorizationInterceptor.java
  src/main/java/com/habitpay/habitpay/global/config/auth/interceptor/SignUpInterceptor.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/habitpay/habitpay/global/util/RequestHeaderUtil.java
Labels: bug, enhancement

#133 Feat/프로필 업데이트 patch member 컨트롤러 분리#132
  src/main/java/com/habitpay/habitpay/domain/member/api/MemberApi.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberActivationService.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberProfileService.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberUpdateService.java
  src/main/java/com/habitpay/habitpay/domain/member/domain/Member.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/ImageUpdateRequest.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/ImageUpdateResponse.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/NicknameDto.java
  src/test/java/com/habitpay/habitpay/domain/api/MemberApiTest.java
Labels: enhancement

#134 Test/member 도메인 컨트롤러 테스트 코드 작성#112
  .github/workflows/api-docs.yaml
  src/docs/asciidoc/api/member.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeUpdateService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApi.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeCancellationService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentService.java
  src/main/java/com/habitpay/habitpay/domain/member/api/MemberApi.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberActivationService.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberProfileService.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberSearchService.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberUpdateService.java
  src/main/java/com/habitpay/habitpay/domain/member/domain/Member.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/ImageUpdateRequest.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/ImageUpdateResponse.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/MemberActivationRequest.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/MemberActivationResponse.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/MemberProfileResponse.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/MemberResponse.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/MemberUpdateRequest.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/NicknameDto.java
  src/main/java/com/habitpay/habitpay/global/config/auth/CorsConfig.java
  src/main/java/com/habitpay/habitpay/global/config/auth/CustomOAuth2LoginSuccessHandler.java
  src/main/java/com/habitpay/habitpay/global/config/auth/CustomOAuth2UserService.java
  src/main/java/com/habitpay/habitpay/global/config/auth/CustomUserDetails.java
  src/main/java/com/habitpay/habitpay/global/config/auth/CustomUserDetailsService.java
  src/main/java/com/habitpay/habitpay/global/config/auth/SecurityConfig.java
  src/main/java/com/habitpay/habitpay/global/config/auth/interceptor/AuthorizationInterceptor.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/TokenProvider.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/TokenService.java
  src/main/java/com/habitpay/habitpay/global/response/ApiResponse.java
  src/main/java/com/habitpay/habitpay/global/response/SuccessResponse.java
  src/main/java/com/habitpay/habitpay/global/util/RequestHeaderUtil.java
  src/test/java/com/habitpay/habitpay/domain/api/MemberApiTest.java
  src/test/java/com/habitpay/habitpay/global/security/WithMockOAuth2User.java
  src/test/java/com/habitpay/habitpay/global/security/WithMockOAuth2UserSecurityContextFactory.java
  src/test/java/com/habitpay/habitpay/member/api/MemberApiTest.java
Labels: enhancement

#136 Test/프로필 업데이트 테스트 코드 작성#135
  src/docs/asciidoc/api/member.adoc
  src/test/java/com/habitpay/habitpay/domain/api/MemberApiTest.java
Labels: documentation, enhancement

#139 fix: 동일한 이메일에 대해 row 가 2개 생성되는 문제 수정 #138
  src/main/java/com/habitpay/habitpay/global/config/auth/CustomOAuth2UserService.java
Labels: bug

#140 Feat/사용자 탈퇴 시 개인 정보 삭제#137
  src/main/java/com/habitpay/habitpay/domain/member/api/MemberApi.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberDeleteService.java
  src/main/java/com/habitpay/habitpay/domain/member/domain/Member.java
  src/main/java/com/habitpay/habitpay/domain/model/BaseTime.java
Labels: enhancement

#142 Test/회원탈퇴 테스트 코드 작성#141
  src/docs/asciidoc/api/member.adoc
  src/test/java/com/habitpay/habitpay/domain/api/MemberApiTest.java
Labels: documentation, enhancement

#145 Test/challenge 컨트롤러 테스트 코드 작성#144
  src/docs/asciidoc/api/challenge.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/test.adoc
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeUpdateService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDetailsResponse.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeResponse.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApi.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeCancellationService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberSearchService.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
  src/main/java/com/habitpay/habitpay/global/config/auth/CustomOAuth2LoginSuccessHandler.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/TokenService.java
  src/test/java/com/habitpay/habitpay/RestDocsControllerTest.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
  src/test/java/com/habitpay/habitpay/domain/member/api/MemberApiTest.java
Labels: documentation, enhancement

#147 Test/챌린지 생성 컨트롤러 테스트 케이스 작성#146
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeCreationRequest.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeCreationResponse.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: documentation, enhancement

#149 Test/챌린지 정보 수정patch challengesid 테스트 코드 작성#148
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengePatchService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengePatchRequest.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengePatchResponse.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: documentation, enhancement

#151 [Test] ChallengePost API: findPost(), findChallengePosts() 메서드를 위한 테스트 코드 작성 #143
  src/docs/asciidoc/api/challengePost.adoc
  src/main/java/com/habitpay/habitpay/domain/challengepost/dto/PostViewResponse.java
  src/test/java/com/habitpay/habitpay/domain/api/ChallengePostApiTest.java
Labels: documentation, enhancement

#152 Test/챌린지 등록 post challengeidenroll 테스트 코드 작성#150
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApi.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentCancellationService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/domain/ChallengeEnrollment.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/dto/ChallengeEnrollmentResponse.java
  src/test/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApiTest.java
Labels: documentation, enhancement

#155 Feat/post member 컨트롤러 제거#154
  src/docs/asciidoc/api/member.adoc
  src/main/java/com/habitpay/habitpay/domain/member/api/MemberApi.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberActivationService.java
  src/main/java/com/habitpay/habitpay/global/config/auth/CustomOAuth2LoginSuccessHandler.java
  src/main/java/com/habitpay/habitpay/global/config/auth/CustomOAuth2UserService.java
  src/main/java/com/habitpay/habitpay/global/config/auth/SecurityConfig.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/TokenService.java
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
  src/test/java/com/habitpay/habitpay/domain/member/api/MemberApiTest.java
Labels: enhancement

#157 [Feat] 컨트롤러 메서드의 반환 타입을 SuccessResponse로 감싸기 #153
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostDeleteService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUpdateService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/dao/ChallengePostRepository.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/dto/PostViewResponse.java
  src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoCreationService.java
  src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoDeleteService.java
  src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoSearchService.java
  src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoUtilService.java
  src/main/java/com/habitpay/habitpay/domain/postphoto/dao/PostPhotoRepository.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/api/TokenApi.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
  src/test/java/com/habitpay/habitpay/domain/api/ChallengePostApiTest.java
Labels: enhancement

#161 [Feat] 페이지네이션 적용을 위한 백엔드 코드 초안 작성 #160
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/dao/ChallengePostRepository.java
  src/main/resources/application.yaml
Labels: enhancement

#163 [Feat] 정상 응답을 SuccessResponse로 감싸는 과정을 컨트롤러가 아닌 서비스 메서드에서 수행하기 #162
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostDeleteService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUpdateService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/api/TokenApi.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
Labels: enhancement

#166 [Feat] 컨트롤러 메서드에서 Pageable을 바로 인자로 받기 #165
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
Labels: enhancement

#167 [Test] 챌린지 포스트 컨트롤러를 위한 테스트 코드 기본 완료 #159
  src/docs/asciidoc/api/challengePost.adoc
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/dto/AddPostRequest.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/dto/ModifyPostRequest.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/dto/PostViewResponse.java
  src/test/java/com/habitpay/habitpay/domain/api/ChallengePostApiTest.java
  src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
Labels: documentation, enhancement

#169 [remove] Pageable과 관련된 불필요한 설정 및 메서드 삭제하기 #168
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
Labels: enhancement

#171 [feat] 챌린지 포스트 삭제 -> SuccessResponse data에 삭제 포스트 id 데이터 반영
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostDeleteService.java
  src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
Labels: enhancement

#173 [test, feat] 리프레시 토큰 테스트 코드 작성, 리프레시 토큰 작은 리팩토링 #172
  src/docs/asciidoc/api/refreshToken.adoc
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/dto/CreateAccessTokenRequest.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/dto/CreateAccessTokenResponse.java
  src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
  src/test/java/com/habitpay/habitpay/domain/refreshtoken/api/RefreshTokenApiTest.java
Labels: documentation, enhancement

#176 feat: 챌린지 총 참여일수 추가 #175
  src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeEnrolledListItemResponse.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: enhancement

#177 [Feat] 챌린지 내 모든 포스트 불러오는 메서드 작성 -> ChallengePost에 Challenge 외래키 연결 #174
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostDeleteService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/dao/ChallengePostRepository.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/domain/ChallengePost.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/dto/AddPostRequest.java
  src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
Labels: enhancement

#179 [Feat] 챌린지 내 공지 포스트만 불러오는 메서드 및 테스트 코드 작성 #178
  src/docs/asciidoc/api/challengePost.adoc
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/dao/ChallengePostRepository.java
  src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
Labels: documentation, enhancement

#181 [Feat] 피드백 반영이자 리팩토링 #180
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
  src/test/java/com/habitpay/habitpay/domain/refreshtoken/api/RefreshTokenApiTest.java
Labels: enhancement

#183 refactor: 챌린지 전체 참여 요일 수 변수명 변경 #182
  src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeEnrolledListItemResponse.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: enhancement

#185 [feat] 공지 포스트 불러오는 메서드와 url 변경 #184
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
Labels: enhancement

#187 [Feat] 테스트 코드 수정 및 index.adoc 파일에 새 문서 추가 #186
  src/docs/asciidoc/index.adoc
  src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
Labels: documentation, enhancement

#190 [Test] 리프레시 토큰으로 재발급 요청 시 발생하는 에러에 대한 테스트 코드 작성 #188
  src/docs/asciidoc/api/refreshToken.adoc
  src/test/java/com/habitpay/habitpay/domain/refreshtoken/api/RefreshTokenApiTest.java
Labels: documentation, enhancement

#192 Feat/예외처리 공통 응답 메세지 형식 적용#189
  src/docs/asciidoc/api/member.adoc
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberDeleteService.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberService.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberUpdateService.java
  src/main/java/com/habitpay/habitpay/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoCreationService.java
  src/main/java/com/habitpay/habitpay/domain/postphoto/exception/CustomPhotoException.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenSearchService.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/TokenAuthenticationFilter.java
  src/main/java/com/habitpay/habitpay/global/error/ErrorResponse.java
  src/main/java/com/habitpay/habitpay/global/error/exception/BusinessException.java
  src/main/java/com/habitpay/habitpay/global/error/exception/EntityNotFoundException.java
  src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
  src/main/java/com/habitpay/habitpay/global/handler/GlobalExceptionHandler.java
  src/test/java/com/habitpay/habitpay/domain/member/api/MemberApiTest.java
Labels: enhancement

#194 Feat/member 도메인 예외처리 공통 응답 처리#193
  src/docs/asciidoc/api/member.adoc
  src/main/java/com/habitpay/habitpay/domain/member/api/MemberApi.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberDeleteService.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberSearchService.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberUpdateService.java
  src/main/java/com/habitpay/habitpay/domain/member/exception/InvalidNicknameException.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
  src/main/java/com/habitpay/habitpay/global/error/exception/InvalidValueException.java
  src/main/java/com/habitpay/habitpay/global/response/SuccessCode.java
  src/test/java/com/habitpay/habitpay/domain/member/api/MemberApiTest.java
Labels: documentation, enhancement

#196 Feat/챌린지 도메인 공통 예외처리 응답 추가#195
  src/docs/asciidoc/api/challenge.adoc
  src/docs/asciidoc/api/member.adoc
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengePatchService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeEnrolledListItemResponse.java
  src/main/java/com/habitpay/habitpay/domain/challenge/exception/ChallengeNotFoundException.java
  src/main/java/com/habitpay/habitpay/domain/challenge/exception/ChallengeStartTimeInvalidException.java
  src/main/java/com/habitpay/habitpay/domain/model/Response.java
  src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
  src/main/java/com/habitpay/habitpay/global/error/exception/ForbiddenException.java
  src/main/java/com/habitpay/habitpay/global/error/exception/InvalidValueException.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: documentation, enhancement

#198 Feat/challengeenrollment 도메인 예외처리 공통 응답 클래스 적용#197
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApi.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentCancellationService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/exception/AlreadyEnrolledChallengeException.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/exception/NotEnrolledChallengeException.java
  src/main/java/com/habitpay/habitpay/global/error/exception/BadRequestException.java
  src/main/java/com/habitpay/habitpay/global/error/exception/ConflictException.java
  src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
  src/main/java/com/habitpay/habitpay/global/response/SuccessCode.java
  src/main/java/com/habitpay/habitpay/global/response/SuccessResponse.java
  src/test/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApiTest.java
Labels: documentation, enhancement

#201 [change] refreshToken 발급 메서드 변경
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
  src/main/java/com/habitpay/habitpay/global/config/auth/CustomOAuth2LoginSuccessHandler.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/TokenService.java
Labels: enhancement

#203 Feat/챌린지 주최자 등록 취소 불가 처리#199
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentCancellationService.java
  src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
  src/test/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApiTest.java
Labels: documentation, enhancement

#205 Fix/챌린지 등록 시 참여 인원 계산 문제 수정#204
  src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentCancellationService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentService.java
Labels: enhancement

#207 Feat/챌린지 상세 정보 조회 시 참여자 프로필 이미지 링크 전송#206
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDetailsResponse.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/dao/ChallengeEnrollmentRepository.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: enhancement

#209 [Feat] 필터에서 발생한 JWT 예외 처리하기 #202
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
  src/main/java/com/habitpay/habitpay/global/config/auth/JwtAuthenticationEntryPoint.java
  src/main/java/com/habitpay/habitpay/global/config/auth/SecurityConfig.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/TokenProvider.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/TokenService.java
Labels: enhancement

#212 Feat/챌린지 시작 전 챌린지 삭제 기능 추가#208
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDeleteService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
  src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
  src/main/java/com/habitpay/habitpay/global/response/SuccessCode.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: enhancement

#213 [Feat] /apply new error resposne type#210
  src/docs/asciidoc/api/challengePost.adoc
  src/docs/asciidoc/api/refreshToken.adoc
  src/main/java/com/habitpay/habitpay/domain/ChallengeAbsenceFee/application/ChallengeAbsenceFeeSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/exception/RecordNotFoundException.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostDeleteService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUpdateService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/exception/PostNotFoundException.java
  src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoCreationService.java
  src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoSearchService.java
  src/main/java/com/habitpay/habitpay/domain/postphoto/exception/CustomPhotoException.java
  src/main/java/com/habitpay/habitpay/domain/postphoto/exception/PhotoNotFoundException.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenSearchService.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenUtilService.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/exception/CustomJwtException.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/exception/RefreshTokenNotFoundException.java
  src/main/java/com/habitpay/habitpay/global/config/auth/JwtAuthenticationEntryPoint.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/TokenProvider.java
  src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
  src/main/java/com/habitpay/habitpay/global/error/exception/UnauthorizedException.java
  src/main/java/com/habitpay/habitpay/global/handler/GlobalExceptionHandler.java
  src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
  src/test/java/com/habitpay/habitpay/domain/refreshtoken/api/RefreshTokenApiTest.java
Labels: documentation, enhancement

#215 test/ 배열 속성의 데이터 타입을 추가 작성, fix/ ErrorCode 파일의 코드 종료문 위치 수정 #214
  src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
  src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
Labels: documentation, enhancement

#219 [Feat] 챌린지 참여 기록이 생성되면, enrollment 엔티티의 successCount의 횟수를 증가시킵니다. #211
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/domain/ChallengeEnrollment.java
  src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
Labels: enhancement

#222 [Feat] 컨트롤러에서 챌린지 포스트 목록 반환 시 Slice 타입으로 반환하기 #220
  src/docs/asciidoc/api/challengePost.adoc
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/dao/ChallengePostRepository.java
  src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
Labels: documentation, enhancement

#223 [feat] 컨트롤러 api 정리 #221
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/api/TokenApi.java
  src/main/java/com/habitpay/habitpay/global/config/auth/SecurityConfig.java
  src/test/java/com/habitpay/habitpay/domain/refreshtoken/api/RefreshTokenApiTest.java
Labels: enhancement

#225 [feat] 챌린지 유효 기간이 아닐 시 포스트 생성 및 수정 불가 #224
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUpdateService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
  src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
Labels: enhancement

#227 [Feat] 회원 탈퇴 시 리프레시 토큰도 레포지토리에서 삭제 #226
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberDeleteService.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenDeleteService.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/dao/RefreshTokenRepository.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/domain/RefreshToken.java
Labels: enhancement

#229 Feat/change error code for post editable#228
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengePatchService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/dto/PostViewResponse.java
  src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoUtilService.java
  src/main/java/com/habitpay/habitpay/domain/postphoto/domain/PostPhoto.java
  src/main/java/com/habitpay/habitpay/domain/refreshtoken/dto/CreateAccessTokenResponse.java
  src/main/java/com/habitpay/habitpay/global/config/auth/CustomOAuth2LoginSuccessHandler.java
  src/main/java/com/habitpay/habitpay/global/config/auth/SecurityConfig.java
  src/main/java/com/habitpay/habitpay/global/config/jwt/TokenProvider.java
  src/main/java/com/habitpay/habitpay/global/error/CustomJwtErrorInfo.java
  src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
  src/main/java/com/habitpay/habitpay/global/handler/GlobalExceptionHandler.java
  src/main/java/com/habitpay/habitpay/global/handler/dto/ExceptionResponse.java
  src/test/java/com/habitpay/habitpay/domain/refreshtoken/api/RefreshTokenApiTest.java
Labels: enhancement
