Repository HabitPay/backend, pull requests merged in 2024-12, with the labels that each got.

#324 Fix/게시물 pageable response dto 1부터 반환하도록 수정#322
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
  src/main/java/com/habitpay/habitpay/global/response/SliceResponse.java
  src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
Labels: bug

#326 [fix] 챌린지 시작 전 취소 안되는 문제 수정#321
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentCancellationService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/domain/ChallengeEnrollment.java
  src/main/java/com/habitpay/habitpay/domain/participationstat/domain/ParticipationStat.java
Labels: bug

#328 [feat] 게시물 이미지 프로필 이미지 업로드 파일 크기 제한 상향#327
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberUpdateService.java
  src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoCreationService.java
  src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoUpdateService.java
  src/main/java/com/habitpay/habitpay/global/util/ImageUtil.java
  src/main/resources/application.yaml
  src/test/resources/application.yaml
Labels: enhancement

#331 [Feat] 챌린지 상세 페이지 우상단의 멤버들 사진을 클릭하면, 챌린지 등록 멤버들 데이터 얻기 #330
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeMemberSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeEnrolledMember.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/dao/ChallengeEnrollmentRepository.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberSearchService.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: documentation, enhancement

#336 Fix/게시물 내용 255자 제한 상향#335
  build.gradle
  src/docs/asciidoc/api/challengePost.adoc
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/domain/ChallengePost.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/dto/AddPostRequest.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/dto/ModifyPostRequest.java
  src/main/java/com/habitpay/habitpay/global/error/ErrorResponse.java
  src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
  src/main/java/com/habitpay/habitpay/global/handler/GlobalExceptionHandler.java
  src/main/resources/db/migration/V202412281745__Change_challengepost_content_length.sql
  src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
Labels: bug

#334 [Refact] SliceResponse 타입 적용 등 소소한 리팩토링 #332
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeMemberSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeEnrolledMember.java
  src/main/java/com/habitpay/habitpay/domain/challengeabsencefee/dto/MemberFee.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberSearchService.java
  src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
  src/test/java/com/habitpay/habitpay/domain/challengeabsencefee/api/ChallengeAbsenceFeeApiTest.java
Labels: documentation, enhancement
