Repository HabitPay/backend, pull requests merged in 2024-10, with the labels that each got.

#257 Feat/챌린지 개별 정보 api 개발#256
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDatesResponse.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeFeePerAbsenceResponse.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeParticipatingDaysResponse.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: enhancement

#259 :bug: fix: docker 명령어 앞 sudo 추가 및 컨테이너 종료 명령어 변경 #258
  down-running-container.sh
Labels: bug

#260 :bug: fix: AWS SSM 실행 jobs 로 분리 #258
  .github/workflows/deploy.yaml
Labels: bug

#262 Feat/챌린지 생성 시 참여 요일 검증 추가#261
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/exception/InvalidChallengeParticipatingDaysException.java
  src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: enhancement

#264 chore: CI GitHub Actions 추가 #263
  .github/workflows/ci.yaml
  src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
Labels: enhancement

#266 [feat] 챌린지 상세 페이지에서 챌린지 전체 벌금값 확인하기 #265
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDetailsResponse.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: enhancement

#269 [Feat] 챌린지 개별 데이터 조회 api : 전체 벌금 조회 추가 #268
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeTotalAbsenceFeeResponse.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: documentation, enhancement

#271 [feat] 챌린지 시작일, 참여 요일, record 등록 등에 관련된 시간 데이터 정합성 이해 및 설정 #270
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
Labels: enhancement

#274 [remove] 챌린지 상세 정보 조회 api 삭제 #273
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDatesResponse.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeFeePerAbsenceResponse.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeParticipatingDaysResponse.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeTotalAbsenceFeeResponse.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: enhancement

#280 remove: absenceTotalFee 컬럼 생성 sql 파일 삭제 #278
  src/main/resources/db/migration/V202410162038__Add_totalAbsenceFee_in_challenge.sql
Labels: bug

#282 [Feat] Challenge 엔티티 클래스에 totalAbsenceFee 필드 추가에 따른 코드 수정 #275
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDetailsResponse.java
  src/main/java/com/habitpay/habitpay/domain/challengeabsencefee/application/ChallengeAbsenceFeeSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/ChallengeSchedulerService.java
  src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/SchedulerTaskHelperService.java
Labels: enhancement

#284 [Feat] 챌린지 상세 페이지 API 데이터에 '오늘 참여 여부' 추가 #283
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDetailsResponse.java
  src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordUtilService.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: documentation, enhancement

#287 [add] 누락 커밋 추가 : 챌린지 디테일 DTO에 '오늘이 참여일인지 여부' 속성 추가 #286
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDetailsResponse.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: documentation, enhancement

#289 [Refactor] 챌린지 상세 정보 조회 api 코드 리팩토링#288
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordUtilService.java
  src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/domain/ChallengeParticipationRecord.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
  src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/SchedulerTaskHelperService.java
Labels: enhancement

#277 [Feat] 타임존 변환 및 설정 시 필요한 문자열 데이터를 환경변수로 설정하기 #276
  build.gradle
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
  src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/SchedulerTaskHelperService.java
  src/main/java/com/habitpay/habitpay/global/config/timezone/TimeZoneConverter.java
  src/main/java/com/habitpay/habitpay/global/config/timezone/TimeZoneProperties.java
  src/main/resources/application.yaml
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
  src/test/resources/application.yaml
Labels: documentation, enhancement

#290 [feat] 스케쥴러 서비스 메서드에 타임존 컨터버 적용하기 #281
  src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/ChallengeSchedulerService.java
  src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/SchedulerTaskHelperService.java
Labels: enhancement

#291 [feat] 챌린지 별 참여 기록을 조회 : 날짜 목록 제공하는 API #285
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeRecordsService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeRecordsResponse.java
  src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: documentation, enhancement

#293 [fix] 스케쥴러 서비스 메서드 : 매일 챌린지 참여 검사 시, totalAbsenceFee가 제대로 합산되지 않는 로직 수정 #292
  src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/SchedulerTaskHelperService.java
Labels: enhancement

#295 [refactor] 챌린지 참여 기록을 위한 메서드 리팩토링 #294
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeRecordsService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeRecords.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeRecordsResponse.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: documentation, enhancement

#297 [refact] verifyChallengePostForRecord 리팩토링 #296
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
Labels: enhancement

#303 [feat] 챌린지 정보 조회 시 사용자의 중도 포기 여부 추가#302
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDetailsResponse.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: enhancement
