Repository HabitPay/backend, pull requests merged in 2025-01, with the labels that each got.

#338 [chore] aws 인프라 이전#337
  .env.sample
  .github/workflows/deploy.yaml
  .gitignore
  conf/nginx.conf
  docker-compose.yaml
  scripts/deploy.sh
  scripts/down-running-container.sh
  scripts/switch.sh
Labels: enhancement

#339 chore: nginx 설정 파일 초기화 명령어 추가 #337
  docker-compose.yaml
  git-pull.sh
Labels: enhancement

#340 fix: nginx 설정 파일 위치 변경 #337
  scripts/switch.sh
Labels: bug

#341 [Feat] 다른 멤버의 챌린지 상세 목록을 불러오는 API 추가 #333
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeEnrolledListItemResponseForMember.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: documentation, enhancement

#343 [Modify] 멤버 별 챌린지 목록을 불러오는 API (반환 타입 수정) #342
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeEnrolledListItemResponseForMember.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: documentation, enhancement

#346 [Feat] 다른 멤버의 프로필 상세 정보를 얻는 api 추가 #344
  src/docs/asciidoc/api/member.adoc
  src/main/java/com/habitpay/habitpay/domain/member/api/MemberApi.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberDetailsService.java
  src/main/java/com/habitpay/habitpay/domain/member/dto/MemberDetailsResponse.java
  src/test/java/com/habitpay/habitpay/domain/member/api/MemberApiTest.java
Labels: documentation, enhancement

#348 [fix] GET /challenges 챌린지 총 참여 일수 dto 변수 추가#347
  src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengePageResponse.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: bug

#353 [fix] 벌금 현황 페이지에서 달성율이 올바르게 표시되지 않는 문제 해결 #352
  src/main/java/com/habitpay/habitpay/domain/challengeabsencefee/dto/MemberFeeView.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/dao/ChallengeEnrollmentRepository.java
Labels: enhancement

#354 [Feat] 호스트의 챌린지 취소 로직 수정 #351
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDeleteService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentCancellationService.java
  src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentSearchService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostDeleteService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUpdateService.java
  src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
  src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/SchedulerTaskHelperService.java
  src/main/java/com/habitpay/habitpay/domain/member/application/MemberUtilsService.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: enhancement

#357 [fix] 이전 실행 도커 이미지 삭제#355
  scripts/down-running-container.sh
Labels: bug

#358 [fix]배포 shell script 수정#355
  git-pull.sh
  scripts/deploy.sh
  scripts/switch.sh
Labels: bug

#359 [fix] nginx 변경 시 컨테이너 실행 시간 기준으로 비교 #355
  scripts/switch.sh
Labels: bug

#360 [fix] 조건문 수정 #355
  scripts/switch.sh
Labels: bug

#361 [fix] 배포 shell script 수정 #355
  scripts/down-running-container.sh
Labels: bug

#363 [feat] 챌린지 종료 이후 정산하는 API 생성 #362
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
  src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSettlementService.java
  src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
  src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/SchedulerTaskHelperService.java
  src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
  src/main/java/com/habitpay/habitpay/global/response/SuccessCode.java
  src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java
Labels: documentation, enhancement
